### ISSUE TITLE
Share Sample Data

### ISSUE THREAD

**Issue by raagas** [evanmunro/restaurant-choice#1]
Hi Evan,
I found your post very interesting. Will it be possible for you to share a sample (10,000 rows) dataset with this post? This will help us in better understanding of your work. 

Thanks!

**Comment by evanmunro** [comment]
Hi, 
Unfortunately I don't have permission to share the underlying data for the project. Is there anything specific I can help clarify ? 

Evan

**Comment by raagas** [comment]
Np Evan! I just want to know the data format. From the data preparation ipython notebook, it's not very clear. I can use some toy data from [this](http://biogeme.epfl.ch/data.html) very standard choice model datasets (or transaction data like [this](https://www.chicagobooth.edu/research/kilts/datasets/dominicks)). Can you just guide me which dataset is closest to your data? Once the data structure is clear, the coding part becomes lot more easier.
Thanks!

**Comment by evanmunro** [comment]
I've written the ChoiceDataset module specifically for the restaurant choice data. I've updated the readme with some additional information on how to extend PyTorch's Dataset class for outside datasets. At some point in the next month, I will update the repository with an example using a simple public dataset (for example the TravelMode dataset from the R package AER), which should clarify things.

**Comment by raagas** [comment]
Thanks Evan! This is very helpful. And it's very nice of you to put so much effort. Really appreciating!!!

**Comment by evanmunro** [comment]
The Jupyter notebook tutorial with sample data from the AER TravelMode package is now in the repository - hope that helps as well!

**Comment by raagas** [comment]
This is perfect! Thanks a lot for all your effort for an unknown. I can't thank you enough!
